### ISSUE TITLE
Time field issue when data is sent to kinesis

### ISSUE THREAD

**Issue by sagargulabani** [aws/amazon-kinesis-streams-for-fluent-bit#83]
Hi, our application logs output JSON, with `time` key in the following format `2020-10-21T06:23:53.835Z`. We are using the aws for fluent bit image and what ends up happening when the record is put into Kinesis is that `time` key becomes `"2020-10-21T06:23:53.835Z98896Z"`. This is our plugin configuration. That Z inbetween causes issues downstream while inserting into ES since the value is not a valid time.
```
 [OUTPUT]
        Name                kinesis
        Match               kube.*
        region              ap-south-1
        stream              test-kinesis-stream
```

**Comment by PettitWesley** [comment]
What is the input for the logs? This is not really an issue with the kinesis output... 

Check out the Fluent Bit parser documentation, I am guessing that is where you timestamp is processed by Fluent Bit:  https://docs.fluentbit.io/manual/pipeline/parsers

I'm not sure how to solve this one. And I am not entirely sure what is going wrong...

> That Z inbetween causes issues downstream while inserting into ES since the value is not a valid time.

It looks like a valid time to me? And you app produces it right? Are you sure this isn't an issue with your ES configuration for parsing the timestamp (not an expert on ES, so forgive me if that is a clueless question).

The only thing I see Fluent Bit doing is increasing the precision for the timestamp, which is weird, but it doesn't seem to be adding the Z.

**Comment by sagargulabani** [comment]
Hi, if you see the end part of the time, it is `53.835 Z  98896Z `, it has this extra `Z` inbetween which makes the timestamp invalid. This is indeed a problem with one of the fluentbit components and not the AWS Kinesis service.
We are using the aws for fluentbit image
eks -> fluentbit -> kubernetes filter -> kinesis output
The reason why I raised this issue here is that output from stdout fluentbit is correct.
I don't think its a problem with the kubernetes filter.

**Comment by PettitWesley** [comment]
I see- can you share your full fluent bit config? And what version you are using. 

This seems to me like it might be something with the parser.

**Comment by bosatsu** [comment]
Here is the full fluentbit configmap and daemonset we deploy.   There are some `##VARIABLES##` that are resolved doing deployment:

**ConfigMap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File        /fluent-bit/parsers/parsers.conf
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        DB                  /var/log/containers/log.db
        Parser              docker
        Skip_Long_Lines     Off
        Refresh_Interval    10
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Merge_Log           On
        Keep_Log            Off
        Labels              Off
        Annotations         Off
    [FILTER]
        Name                modify
        Match               kube.*
        Rename  log message
    [OUTPUT]
        Name                kinesis
        Match               kube.*
        region              ##AWS_REGION##
        stream              ##APP-STREAM##
    @INCLUDE custom.conf
    @INCLUDE systemd.conf
  systemd.conf: |
    [INPUT]
        Name                systemd
        Tag                 systemd.*
        Path                /var/log/journal
        Systemd_Filter      _SYSTEMD_UNIT=docker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail      true
    [OUTPUT]
        Name                kinesis
        Match               systemd.*
        region              ##AWS_REGION##
        stream              ##SYS-STREAM##
```

**Daemonset**
```
# https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: fluentbit
---
# https://github.com/aws-samples/amazon-ecs-fluent-bit-daemon-service/blob/master/eks/eks-fluent-bit-daemonset-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pod-log-reader
  namespace: fluentbit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-log-crb
  namespace: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-log-reader
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: fluentbit
---
# https://github.com/aws-samples/amazon-ecs-fluent-bit-daemon-service/blob/master/eks/eks-fluent-bit-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: aws-for-fluent-bit
        image: amazon/aws-for-fluent-bit:2.3.1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: mnt
        hostPath:
          path: /mnt
```
